/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.automatedresttesting;

import org.xtext.example.automatedresttesting.AutomatedRestTestingStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AutomatedRestTestingStandaloneSetup extends AutomatedRestTestingStandaloneSetupGenerated {
  public static void doSetup() {
    AutomatedRestTestingStandaloneSetup _automatedRestTestingStandaloneSetup = new AutomatedRestTestingStandaloneSetup();
    _automatedRestTestingStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
