/**
 *
 * $Id$
 */
package automatedresttesting.validation;

import automatedresttesting.AttributeType;
import automatedresttesting.Restriction;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link automatedresttesting.Attribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValidator {
	boolean validate();

	boolean validateValue(String value);
	boolean validateRestrictions(EList<Restriction> value);
	boolean validateType(AttributeType value);
}
