/**
 *
 * $Id$
 */
package automatedresttesting.validation;

import automatedresttesting.Element;
import automatedresttesting.RestService;
import automatedresttesting.Test;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link automatedresttesting.AutomatedRestTesting}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AutomatedRestTestingValidator {
	boolean validate();

	boolean validateUrl(String value);
	boolean validateTests(EList<Test> value);
	boolean validateServices(EList<RestService> value);
	boolean validateDataElements(EList<Element> value);
}
