/**
 *
 * $Id$
 */
package automatedresttesting.validation;

import automatedresttesting.Assertion;
import automatedresttesting.MappingElement;
import automatedresttesting.RestService;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link automatedresttesting.Test}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestValidator {
	boolean validate();

	boolean validateDescription(String value);
	boolean validateAssertions(EList<Assertion> value);
	boolean validateName(String value);
	boolean validateService(RestService value);
	boolean validateMappings(EList<MappingElement> value);
}
