/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.automatedresttesting.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.automatedresttesting.ui.internal.AutomatedresttestingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AutomatedRestTestingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AutomatedresttestingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AutomatedresttestingActivator.getInstance().getInjector(AutomatedresttestingActivator.ORG_XTEXT_EXAMPLE_AUTOMATEDRESTTESTING_AUTOMATEDRESTTESTING);
	}
	
}
