/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.automatedresttesting.ide


/**
 * Use this class to register ide components.
 */
class AutomatedRestTestingIdeModule extends AbstractAutomatedRestTestingIdeModule {
}
