/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.automatedresttesting.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.automatedresttesting.ui.AbstractAutomatedRestTestingUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AutomatedRestTestingUiModule extends AbstractAutomatedRestTestingUiModule {
  public AutomatedRestTestingUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
