/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.automatedresttesting.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAutomatedRestTestingScopeProvider extends DelegatingScopeProvider {
}
