/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.automatedresttesting.ide;

import org.xtext.example.automatedresttesting.ide.AbstractAutomatedRestTestingIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AutomatedRestTestingIdeModule extends AbstractAutomatedRestTestingIdeModule {
}
