/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.automatedresttesting.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.automatedresttesting.ui.internal.AutomatedresttestingActivator;

public class AutomatedRestTestingUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AutomatedresttestingActivator.getInstance().getInjector("org.xtext.example.automatedresttesting.AutomatedRestTesting");
	}

}
