/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.automatedresttesting.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AutomatedRestTestingAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/automatedresttesting/parser/antlr/internal/InternalAutomatedRestTesting.tokens");
	}
}
